import { NextRequest, NextResponse } from "next/server";
import { query } from "@/lib/db";
import { serveLocalMedia } from "@/lib/local-media-response";
import { mediaDiskRootForKind } from "@/lib/media-assets";

export const runtime = "nodejs";

/**
 * Serves locally hosted media under an opaque key.
 *
 * The storage path records which source supplied an image, which is useful
 * internally and has no business being in a URL a browser requests. This
 * resolves the key to a path server-side; the path is never disclosed.
 */
export async function GET(req: NextRequest, { params }: { params: Promise<{ key: string }> }) {
  const { key } = await params;

  // Keys are generated by us and are always plain alphanumerics; rejecting
  // anything else keeps arbitrary input away from the lookup and the filesystem.
  const cleaned = key.replace(/\.[a-z0-9]+$/i, "");
  if (!/^[A-Za-z0-9]{8,64}$/.test(cleaned)) {
    return NextResponse.json({ error: { code: "not_found", status: 404 } }, { status: 404 });
  }

  const rows = await query<{ kind: string; relative_path: string }>(
    "SELECT kind, relative_path FROM media_assets WHERE media_key = $1",
    [cleaned],
  );
  if (rows.length === 0) {
    return NextResponse.json({ error: { code: "not_found", status: 404 } }, { status: 404 });
  }

  const root = mediaDiskRootForKind(rows[0].kind);
  if (!root) {
    return NextResponse.json({ error: { code: "not_found", status: 404 } }, { status: 404 });
  }

  return serveLocalMedia(req, rows[0].relative_path.split("/"), root);
}
